### ISSUE TITLE
bootstrap own libavcodec/ffmeg

### ISSUE THREAD

**Issue by h0lzi** [gewalker/plex-linux#1]
Quite early to request this but it might be good to bootstrap own libavcodec to have the most recent. Depending on distro this is build on it might be quite old. Even newest ubuntu is still on 0.7.x branch iirc. Which does not have the multithread patches etc.

**Comment by gewalker** [comment]
This project links Elan's plex ffmpeg fork rather than using an external
ffmpeg from the OS.  I've created a fork of it called plex-ffmpeg-linux.
 We're trying to keep the changes to the minimum required to have it work
so that they can be easily merged back into the main Plex tree.  We're
aiming toward a unified build and release schedule with Linux clients
released alongside the OSX and Windows ones.

Thanks for taking an interest in the code.  Hope to hear more from you.

On Sun, Dec 4, 2011 at 11:43 AM, h0lzi <
reply@reply.github.com

> wrote:
> 
> Quite early to request this but it might be good to bootstrap own
> libavcodec to have the most recent. Depending on distro this is build on it
> might be quite old. Even newest ubuntu is still on 0.7.x branch iirc. Which
> does not have the multithread patches etc.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/gewalker/plex-linux/issues/1

## 

Gary E. Walker
email/gtalk: gewalker@gmail.com | twitter: @gewalker
The universe is expanding because it's trying to get away from the Internet.
PGP public key: http://gewalker.googlepages.com/pgp.txt

**Comment by gewalker** [comment]
Closing issue as we are already using our own ffmpeg build.

**Comment by elan** [comment]
And just to clarify, it's based on very near HEAD ffmpeg + a few patches.

**Comment by h0lzi** [comment]
ok. I did follow the wrong code path then :)
I did wonder because the readme states: libavcodec-dev libavformat-dev libswscale-dev libavdevice-dev.
Which should not be needed if it's build private.
Anyway will check code today...

**Comment by elan** [comment]
Yeah, that readme is wrong or out of date :)
